enum ScreenActionType {
    LOGIN_SCREEN = "LOGIN_SCREEN",
    HOME = "home",
    WIFI = "WIFI",
    VOUCHER = "VOUCHER",
    PROFILES = "PROFILES",
    LOCATION = "LOCATION",
    ONBOARDING1 = "ONBOARDING1",
    LIST_LOCATION = "LIST_LOCATION",
    DETAIL_LOCATION_DIRECTION = "DETAIL_LOCATION_DIRECTION",
    DETAIL_LIST_LOCATION_DIRECTION = "DETAIL_LIST_LOCATION_DIRECTION",
    DETAIL_LIST_LOCATION = "DETAIL_LIST_LOCATION",
    OPEN_MAP_LOCATION = "OPEN_MAP_LOCATION",
}

export default ScreenActionType;