enum LocationActionType {
    GET_LOCATION_MEMBER = "GET_LOCATION_MEMBER",
    GET_DETAIL_LOCATION = "GET_DETAIL_LOCATION",
    DETAIL_ARTICLE = "DETAIL_ARTICLE",
    BUY_VOUCHER = "BUY_VOUCHER",
    SET_POP = "SET_POP",
    VAL_VOUCHER = "VAL_VOUCHER",
}


export default LocationActionType;